# -*- coding: utf-8 -*-
"""Copy of Untitled59.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qESlbRKIxBxp_YtMI9vO3k6x9pNVNoF_
"""

for x in range(6):
    if (x==3 or x==6):
        continue
    print(x,end=' ')
print("\n")