# -*- coding: utf-8 -*-
"""Copy of Untitled62.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15cM3HtzYMUrPmMo85xEnblU-VMQatkIX
"""

def chars_mix_up(a, b):  
  new_a = b[:2] + a[2:] 
  new_b = a[:2] + b[2:]  
  return new_a + ' ' + new_b 
 print(chars_mix_up('abc', 'xyz'))