# -*- coding: utf-8 -*-
"""Copy of Untitled64.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIR50VL8P56YcGDVHYu3TzcIJSnAEBz1
"""

user_input = input("What is your Name? ")
print("My Name is ", user_input.upper())
print("My Name is ", user_input.lower())