# -*- coding: utf-8 -*-
"""Copy of Untitled60.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Twd5Mzrpg4YjcwVWvLqd-GWzuX58jrao
"""

str="Anil Kumar" 
x=len(str) 
print(x)